### ISSUE TITLE
Umbraco Deploy conflict

### ISSUE THREAD

**Issue by ronaldbarendse** [DigitalMomentum/Umbraco7-Videolizer#11]
When restoring an Umbraco Cloud website, Umbraco Deploy is used to restore all metadata (from the `data/revision/*.uda` files): this ensures all UDIs are equal on all environments (e.g. cloud and local). But Videolizer is creating havoc by creating a new data type on startup using a migration:

https://github.com/DigitalMomentum/Umbraco7-Videolizer/blob/ce6b504f8f398b2a923237f5dec1b77ccfa06078/Videolizer/Migrations/Version_1_1_0.cs#L18-L30

This data type has the same name/alias but a different UDI, so Umbraco Deploy throws this exception:

```
Umbraco.Deploy.Exceptions.ArtifactCollisionException: Some artifacts collide on unique identifiers.
This means that they have different Udis, yet
they refer to the same unique Umbraco object
and therefore cannot be processed.
---------------------------------------------
Collisions for entity type "data-type": 
  Collisions for unique identifier "Videolizer":
    UdaFile: ~/data/revision/data-type__559228dbcab74c9dac9cb95eb0e0f4cb.uda
    UdaFile: ~/data/revision/data-type__cbafca0cf38a4aa0abe0d2fd1a477991.uda
```

A possible workaround is to rename the data type before use, so the one restored by Umbraco Deploy is different then the one created by the migration. After the deploy, the newly created could be removed again to ensure the environments are kept the same.

I know there's not (yet) a 'right way' to create these items in Umbraco from a NuGet package, so maybe just adding a condition to this migration to prevent making the data type would be the best option. This condition could be based on the installed assembly `Umbraco.Deploy` or an application setting...

**Comment by dinc5150** [comment]
I've just pushed up Version 2.1.4 on Nuget & Our which should resolve this issue. I don't have an Umbraco Cloud account and haven't had a chance to set one up to test, so please stop back when you get the chance and let me know if it fixes the problem for you.

**Comment by ronaldbarendse** [comment]
I can confirm this bugfix works as expected: the data type isn't created and Umbraco Deploy happily restores all meta-data. Thanks for fixing this so quickly #h5yr!

**Comment by dinc5150** [comment]
No worries, thanks for the update!
