### ISSUE TITLE
Use PascalCasing for class properties

### ISSUE THREAD

**Issue by HarveyWilliams** [DigitalMomentum/Umbraco7-Videolizer#3]
Documentation: https://msdn.microsoft.com/en-us/library/ms229043(v=vs.110).aspx

For example, the `VideolizerVideo.cs` class should have:

```
public string Url { get; set; }
```

Not:

```
public string url { get; set; }
```

**Comment by dinc5150** [comment]
Thanks @HarveyWilliams, I'm terrible at keeping consistent with capitalisations.

I will wait till the next major release to clean up the casing so that I don't break existing sites.

**Comment by dinc5150** [comment]
I have depreciated the old methods and will pull them out totally in a few versions time as its quite confusing to have both .Url and .url.
