### ISSUE TITLE
Include .dll.xml in package

### ISSUE THREAD

**Issue by HarveyWilliams** [DigitalMomentum/Umbraco7-Videolizer#4]
You have commented your C# with `<summary>` tags which can be useful for Intellisense. An XML file can be generated by VS on compilation which includes extra Intellisense information which is generated from the summaries.

It would be nice if the package could include this XML file.

**Comment by dinc5150** [comment]
Thanks for the tip @HarveyWilliams . I've enabled it and is now included in the build
