### ISSUE TITLE
Installing DigitalMomentum.Videolizer on non web project adds Videolizer to App_Plugins

### ISSUE THREAD

**Issue by HarveyWilliams** [DigitalMomentum/Umbraco7-Videolizer#5]
Hi, glad to see you're keeping this project up to date.

In my solution, I have separated my projects into 3:

- Website.Core (C# files)
- Website.Web (Umbraco, scripts, css and views)
- Umbraco.Web.PublishedContentModels (uses a slightly custom implementation of the Models Builder based on [this guide](https://www.dot-see.com/en/blog/how-to-use-modelsbuilder-in-a-multi-project-umbraco-solution))

If I install this Videolizer package onto Website.Web, then I can create the datatype in Umbraco. But when I try and build my content models (which are located in Umbraco.Web.PublishedContentModels), I get the following error:

```
The type or namespace name 'Videolizer' could not be found (are you missing a using directive or an assembly reference?)
```

This is because the Models Builder needs the `Videolizer.dll` to compile the models properly.

However, installing the package on other projects adds `\App_Plugins\Videolizer\` to those projects. Since my Website.Core and Umbraco.Web.PublishedContentModels projects are not web projects, these extra files aren't needed.

My request is for you to create another NuGet package called `DigitalMomentum.Videolizer.Core` which can be installed on any projects which are not web projects.

Sorry for the long winded explanation.

**Comment by dinc5150** [comment]
Thanks Harvey,

I set my projects up the same way, so totally get where your coming from. 
I haven't tested them on a site using models builder with that setup, but I'm sure that I'll come up against the same problem. I would rather not have 2 separate Nuget packages but not sure of any other way around it. I'll have bit more of a think. I know its not nice, but the App_plugins folder in the models project shouldn't cause any grief for now.

P.S. haven't had time to test the new updates properly yet so haven't put it up on Nuget, but the new version will be coming soon

**Comment by dinc5150** [comment]
I have split the project into Videolizer (the Umbraco Migration Install Process and App_Plugins Folder) and Videolizer.Core (The model and Property Value Converter). This way Videolizer.Core could actually be used on non-Umbraco contexts to get video information. It could become a useful utility class as I add more functionality and metadata down the track. I haven't setup the new Nuget Packages as yet, but hope to git it released in the next week. Thanks for the suggestions!

**Comment by HarveyWilliams** [comment]
@dinc5150 Nice! Looking forward to using the next release.
