### ISSUE TITLE
Checking if VideolizerVideo is null

### ISSUE THREAD

**Issue by HarveyWilliams** [DigitalMomentum/Umbraco7-Videolizer#7]
I ran this code:

```
@if (Model.Video != null)
{
    @(Model.Video.GetSimpleEmbed("100%", "360px"))
}
```

I expected nothing to be rendered if no video has been put in to the datatype, but instead the following rendered:

```
<iframe src="" style="" webkitallowfullscreen="" mozallowfullscreen="" allowfullscreen="" width="100%" height="360px" frameborder="0"></iframe>
```

Instead, I found that the `!Model.Video.id.IsNullOrWhiteSpace()` check worked as I wanted.

I feel like the model for the datatype should be null if no value has been set, similar to how IPublishedContent properties tend to work.

The only issue with updating it to work as I expect it to, is that it could cause a lot of null references on projects which expect `Model.Video` to not be null.

**Comment by dinc5150** [comment]
The best function to call is `Model.Video.HasVideo()` to check if there is a video. 

I think that I should change `@(Model.Video.GetSimpleEmbed("100%", "360px")) to return an empty string if there is no video. So I'll look at changing it. 

I just quickly checked the model and I'm returning a blank object if its null. I'm not sure why I have done that, so I'll check first before making any changes to returning it as null. 

I like the idea of the simplicity of calling `Model.Video.GetSimpleEmbed()` without having to put an if statement around it to check if there is a video.

Thanks for all the feedback. Its been really useful!

**Comment by HarveyWilliams** [comment]
I agree on `.GetSimpleEmbed()` returning an empty string.

I guess this `.HasVideo()` method must be a new one as my model doesn't have that method. Looking forward to using the next release.

**Comment by dinc5150** [comment]
Sorry, `HasVideo()` must have been a function that I've added along the way since the last release. I have just updated a fix, so that `GetSimpleEmbed()` will now return an empty string if there is no video.
