### ISSUE TITLE
Forcefully logged out of Umbraco if YouTube or Vimeo API's return a HTTP 403 response

### ISSUE THREAD

**Issue by dinc5150** [DigitalMomentum/Umbraco7-Videolizer#8]
If an incorrect API key is entered, YouTube and Vimeo return a 403 Forbidden response. Umbraco picks up on this and mistakenly logs us out. This will easily confuse people if they enter the wrong API key.

Solution: Instead of the property editor querying directly to the YouTube/Vimeo API, we will query a Videolizer Controller which will handle the YouTube/Vimeo API calls from the server. This will allow more control over the response and simplify the front-end JavaScript

**Comment by dinc5150** [comment]
Added umbIgnoreErrors the the AJAX request to tell Umbraco to ignore the error response. - [U4-5588](http://issues.umbraco.org/issue/U4-5588)

Thanks for the tip @Shazwazza!

**Comment by Shazwazza** [comment]
whoohoo glad you found the ticket too :)
